version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web interface
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - MONGODB_URL=your_hosted_mongodb_url  # Replace with your MongoDB URL
      - DATABASE_NAME=image_search
      - CRAWLER_THREADS=4
      - CRAWLER_DEPTH=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
